Updated CICD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,14 +25,14 @@ jobs:
 
       # Install dependencies
       - name: Install dependencies
-        run: cd react && npm install
+        run: npm install
 
       # Build the project (e.g. React, Angular, etc.)
       - name: Build project
-        run: cd react && npm run build
+        run: npm run build
 
       - name: Verify Build Directory
-        run: ls -la react/dist || echo "⚠️ react/dist directory not found!"
+        run: ls -la dist || echo "⚠️ react/dist directory not found!"
 
 
       - name: Deploy to Firebase
