test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,25 +15,25 @@ jobs:
 
     steps:
       # Checkout the repository
-      - name: Checkout repository
-        uses: actions/checkout@v3
+      # - name: Checkout repository
+      #   uses: actions/checkout@v3
 
-      # Set up Node.js
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '20'  # Or your desired version of Node.js
+      # # Set up Node.js
+      # - name: Set up Node.js
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: '20'  # Or your desired version of Node.js
 
-      # Install dependencies
-      - name: Install dependencies
-        run: npm install
+      # # Install dependencies
+      # - name: Install dependencies
+      #   run: npm install
 
-      # Build the project (e.g. React, Angular, etc.)
-      - name: Build project
-        run: npm run build
+      # # Build the project (e.g. React, Angular, etc.)
+      # - name: Build project
+      #   run: npm run build
 
-      - name: Verify Build Directory
-        run: ls -la dist || echo "⚠️ react/dist directory not found!"
+      # - name: Verify Build Directory
+      #   run: ls -la dist || echo "⚠️ react/dist directory not found!"
 
       - name: Deploy to Firebase
         uses: FirebaseExtended/action-hosting-deploy@v0
